Season: 2013-14
SeasonType: Regular Season
MeasureType: Base
PerMode: Totals
PlusMinus: N
PaceAdjust: N
Rank: N
Outcome: ''
Location: ''
Month: 0
SeasonSegment: 
DateFrom: ''
DateTo: ''
OpponentTeamID: 0
VsConference: ''
VsDivision: ''
GameSegment: ''
SeasonSegment: ''
Period: 0
LastNGames: 0
GameScope: ''
PlayerExperience: ''
PlayerPosition: ''
StarterBench: ''