swagger: '2.0'
info:
  title: Parlmap API
  version: 0.0.1
paths:
  /miserables:
    get:
      summary: Les Mis
      operationId: controller.miserables
      responses:
        200:
          description: Something
  /:
    get:
      summary: Teams Details
      operationId: controller.test
      responses:
        200:
          description: Task successfully created
          schema:
            type: string

