apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: api-server
  name: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: api-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: api-server
    spec:
      containers:
      - image: tiao/nba-rank:api-server
        name: api-server
        ports:
        - containerPort: 8080
        resources: {}
status: {}
