apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: api-server
  name: api-server
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: api-server
status:
  loadBalancer: {}
