apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: task-queue
    role: result-backend
    tier: backend
  name: redis-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-queue
      role: result-backend
      tier: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: task-queue
        role: result-backend
        tier: backend
    spec:
      containers:
      - image: redis
        name: redis-master
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
status: {}
