apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: task-queue
    role: result-backend
    tier: backend
  name: redis-master
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: task-queue
    role: result-backend
    tier: backend
status:
  loadBalancer: {}
